# Generated by Django 2.1 on 2018-09-21 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creation', '0004_event_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='user',
        ),
    ]
