# Generated by Django 2.1.1 on 2018-09-26 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creation', '0006_auto_20180923_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='admin',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='users',
            field=models.ManyToManyField(related_name='event_user', to='creation.User'),
        ),
    ]
